export const initialAgentValues = {
  identity: "",
  style: "",
  response: "",
  language: "",
  voice_id: "",
  ambient_sound: "",
  responsiveness: 100,
  interruption_sensitivity: 100,
  enable_backchannel: true,
  backchannel_frequency: 100,
  backchannel_words: "",
  boosted_keywords: "",
  enable_transcription_formatting: false,
  reminder_trigger_ms: 0,
  reminder_max_count: 0,
  normalize_for_speech: false,
  enable_voicemail_detection: false,
  voicemail_message: "",
  voicemail_content: "",
  voicemail_detection_timeout_ms: 100,
  end_call_after_silence_ms: 40,
  max_call_duration_ms: 40,
  opt_out_sensitive_data_storage: true,
  //Todo
  fallback_voice_ids: [],
  webhook_url: "",
  pronunciation_dictionary: {},
  voice_model: "",
  voice_temperature: 1,
  voice_speed: 1,
  volume: 1,
  ambient_sound_volume: 1,
  //Todo end
};
