export const BASE_URL = "https://staging.sendcast.io/api/app/v1"
export const LOGIN_URL = "/auth/login"
export const SIGN_UP_URL = "/auth/signup"
export const DELETE_SESSION = "/auth/session"
export const REQUEST_PASSWORD = "/auth/password/request"
export const CHANGE_PASSWORD = "/account/password/change"