export const BASE_URL = "http://13.201.161.105:8000/api/app/v1"
export const LOGIN_URL = "/auth/login"
export const SIGN_UP_URL = "/auth/signup"
export const DELETE_SESSION = "/auth/session"
export const REQUEST_PASSWORD = "/auth/password/request"